name: test on macos

on: 
  push:
  schedule:    
    - cron: "*/30 * * * *"

jobs:
  test-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - run: |
        python3 test-macos.py
